apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: admq
  labels:
    app: broker
spec:
  ports:
    - port: 8080
      name: http
    - port: 6650
      name: pulsar
  clusterIP: None
  selector:
    app: broker
---
apiVersion: v1
kind: Service
metadata:
  name: broker-nodeport
  namespace: admq
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: pulsar
      port: 6650
      targetPort: 6650
      nodePort: 30050
  selector:
    app: broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: admq
spec:
  selector:
    matchLabels:
      app: broker
  replicas: 3
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: "mz1999/admq:2.1.0"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >
              sed -i "s/advertisedAddress=/advertisedAddress=${advertisedAddress}/g" /admq/config/broker.conf &&
              /admq/bin/admq broker
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 6650
              name: pulsar
          env:
            - name: advertisedAddress
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
