apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: admq
  labels:
    app: zk
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
---
## Define a StatefulSet for ZK servers
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: admq
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zookeeper
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
    spec:
      # Make sure multiple pods of ZK don't get scheduled on the
      # same node, unless there are no other available nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - zk
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zookeeper
          image: "mz1999/admq:2.1.0"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256M"
              cpu: "0.5"
          command: ["sh", "-c"]
          args:
            - >
              /admq/bin/generate-zookeeper-config.sh /admq/config/zookeeper.conf &&
              /admq/bin/admq zookeeper
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOOKEEPER_SERVERS
              value: zk-0,zk-1,zk-2
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "/admq/bin/zookeeper-ruok.sh"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "/admq/bin/zookeeper-ruok.sh"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: datadir
              mountPath: /admq/data
      volumes:
        - name: datadir
          emptyDir: {}
